import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import LoginForm from "../components/Login/LoginForm";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="w-screen h-screen flex flex-col justify-center items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex bg-white justify-center h-[600px] w-[1000px] overflow-hidden rounded-xl">
        <LoginForm />
        <div className="relative w-full ">
          <Image src="/images/bg.jpg" layout='fill' className="object-cover" alt='background' />
        </div>
      </div>
    </div>
  );
};

export default Home;
